In [42]:
import numpy as np
import pandas as pd

class Person:

    def __init__(self, selections) -> None:
        pass

    def change_vote(self, A, B) -> bool:
        return (A >= B) and (A + B < 5)

class Group:

    def __init__(self, selections, selectors) -> None:
        self.selectionsnum = selections
        self.selectorsnum = selectors
        self.selections = np.arange(self.selectionsnum)
        self.selectors = [Person(self.selections) for _ in np.arange(self.selectorsnum)]

    def convert(self, A:int, B:int) -> bool:
        if sum([person.change_vote(A, B ) for person in self.selectors]) / self.selectorsnum >= 0.5:
            return True
        return False

    def convertions(self, A) -> list:
        return [selection for selection in self.selections if self.convert(A, selection)]

    def approachable(self, A:int, B:int) -> bool:
        if A == B:
            return True

        visited = set()  # 用于存储已经访问过的点
        queue = self.convertions(A) # 初始化队列，起始点入队

        while queue:
            vertex = queue.pop(0)  # 从队列中取出一个点
            visited.add(vertex)  # 标记该点为已访问

            # 遍历所有从当前点可以直接到达的点
            for neighbor in self.convertions(vertex):
                if neighbor not in visited:  # 如果该点还没有被访问过
                    if neighbor == B:
                        return True
                    queue.append(neighbor)  # 将该点入队
                    
        return False
                
    def draw_approachable_matrix(self) -> np.array:
        matrix = np.full((self.selectionsnum, self.selectionsnum), 0)
        for i in self.selections:
            for j in self.selections:
                if self.approachable(i , j):
                    matrix[i, j] = 1
                
        return matrix


In [43]:
selections = 5
selectors = 5
a = Group(selections, selectors).draw_approachable_matrix()
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
